version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'my_database1'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '15931'
      MYSQL_ROOT_PASSWORD: '15931'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql