# Generated by Django 5.0.3 on 2024-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='media/cat_images/', verbose_name='Изображение котика'),
        ),
    ]
