# Generated by Django 5.0.3 on 2024-04-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catshop', '0002_alter_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='species',
            field=models.CharField(default=0, max_length=100, verbose_name='Вид котика'),
            preserve_default=False,
        ),
    ]
